# Generated by Django 5.1.6 on 2025-09-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='tokopedia_store_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tokopedia_url',
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='tiktok_store_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tiktok_url',
            field=models.URLField(blank=True, verbose_name='Link Tiktok'),
        ),
    ]
